### ISSUE TITLE
代码跑不通

### ISSUE THREAD

**Issue by wyoldfour** [houbb/data-factory#1]
Exception in thread "main" java.lang.IllegalArgumentException: Can not set int field com.example.mytest.User.age to null value
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(UnsafeIntegerFieldAccessorImpl.java:80)
	at java.lang.reflect.Field.set(Field.java:764)
	at com.github.houbb.data.factory.core.api.data.aggregate.BeanData.build(BeanData.java:41)
	at com.github.houbb.data.factory.core.core.Data.build(Data.java:23)
	at com.github.houbb.data.factory.core.util.DataUtil.build(DataUtil.java:29)
	at com.example.mytest.User.main(User.java:73)

**Comment by houbb** [comment]
能将你的 User 对象贴出来我看看吗？以及测试部分的代码。

我刚才跑了下 master 测试案例。

```java
User user = DataUtil.build(User.class);
System.out.println(user);
```

结果如下：

```
User{name='op', age=42, birthday=Tue Nov 19 19:04:50 CST 2019, stringList=[4bMrhSgX], statusEnum=F, map={kXyes=35YO}}
```

其中 [User.java](https://github.com/houbb/data-factory/blob/master/data-factory-core/src/test/java/com/github/houbb/data/factory/core/model/User.java)

**Comment by wyoldfour** [comment]
`public class User {
    private String name;
    private int age;
    private Date birthday;
    private List<String> stringList;
    private StatusEnum statusEnum;
    private Map<String, String> map;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return age;
    }
    public void setAge(int age) {
        this.age = age;
    }
    public Date getBirthday() {
        return birthday;
    }
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public List<String> getStringList() { return stringList; }
    public void setStringList(List<String> stringList) {
        this.stringList = stringList;
    }
    public StatusEnum getStatusEnum() {
        return statusEnum;
    }
    public void setStatusEnum(StatusEnum statusEnum) {
        this.statusEnum = statusEnum;
    }
    public Map<String, String> getMap() {
        return map;
    }
    public void setMap(Map<String, String> map) {
        this.map = map;
    }
    public static void main(String[] args) {
        User user = DataUtil.build(User.class);
        System.out.println(user);
    }
}`
pom
`   <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>data-factory-core</artifactId>
            <version>0.0.3</version>
        </dependency>

    </dependencies>`

**Comment by wyoldfour** [comment]
`
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.houbb</groupId>
            <artifactId>data-factory-core</artifactId>
            <version>0.0.3</version>
        </dependency>

    </dependencies>
`

**Comment by wyoldfour** [comment]
`
public class User {
    private String name;
    private int age;
    private Date birthday;
    private List<String> stringList;
    private StatusEnum statusEnum;
    private Map<String, String> map;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public int getAge() {
        return age;
    }
    public void setAge(int age) {
        this.age = age;
    }
    public Date getBirthday() {
        return birthday;
    }
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public List<String> getStringList() { return stringList; }
    public void setStringList(List<String> stringList) {
        this.stringList = stringList;
    }
    public StatusEnum getStatusEnum() {
        return statusEnum;
    }
    public void setStatusEnum(StatusEnum statusEnum) {
        this.statusEnum = statusEnum;
    }
    public Map<String, String> getMap() {
        return map;
    }
    public void setMap(Map<String, String> map) {
        this.map = map;
    }
    public static void main(String[] args) {
        User user = DataUtil.build(User.class);
        System.out.println(user);
    }
}
`

**Comment by wyoldfour** [comment]
`
public class User {

    private String name;

    private int age;

    private Date birthday;

    private List<String> stringList;

    //S/F 的枚举
    private StatusEnum statusEnum;

    private Map<String, String> map;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public List<String> getStringList() {
        return stringList;
    }

    public void setStringList(List<String> stringList) {
        this.stringList = stringList;
    }

    public StatusEnum getStatusEnum() {
        return statusEnum;
    }

    public void setStatusEnum(StatusEnum statusEnum) {
        this.statusEnum = statusEnum;
    }

    public Map<String, String> getMap() {
        return map;
    }

    public void setMap(Map<String, String> map) {
        this.map = map;
    }

    public static void main(String[] args) {
        User user = DataUtil.build(User.class);
        System.out.println(user);
    }
}
`

**Comment by houbb** [comment]
ORZ... 忽然发现这个问题忘记回答了。
应该是你忘记开启 【如果是 idea，测试的时候 Enable Annotation Processing。】
我在 v0.0.5 版本将移除对于运行时注解的依赖。

**Comment by hyzhan43** [comment]
IDEA，开启Enable Annotation Processing，好像也是无效的
User{name='null', age=null, birthday=null, stringList=null, statusEnum=null, map=null}。

**Comment by hyzhan43** [comment]
`
                // 加上这个默认值
                Object value = DataUtil.build(context, fieldClass);
                DataFactory dataFactory = field.getAnnotation(DataFactory.class);
                if (dataFactory != null && dataFactory.data() != IData.class) {
                    value = ClassUtil.newInstance(dataFactory.data()).build(context, fieldClass);
                } else if (dataFactory != null) {
                    // 默认的实现
                    DefaultDataFactoryAnnotationData annotationData = new DefaultDataFactoryAnnotationData();
                    value = annotationData.build(context, fieldClass);
                }

                // 是否为自定义注解
                IAnnotationData annotationData = InnerDataUtil.getDefineDataAnnotation(field);
                if (annotationData != null) {
                    value = annotationData.build(context, fieldClass);
                }`
如果不加注解，这样全部都为null了，应该有个兜底的方案吧？ 默认是随机参数，如果有注解就生成注解参数，如果有自定义就生成自定义。

**Comment by houbb** [comment]
感谢提醒。v1.1.0 已经修复这个问题。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hyzhan43 ***@***.***&gt;
发送时间: 2021年8月3日 11:41
收件人: houbb/data-factory ***@***.***&gt;
抄送: 老马啸西风 ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[houbb/data-factory] 代码跑不通 (#1)





 
`
 // 加上这个默认值
 Object value = DataUtil.build(context, fieldClass);
 DataFactory dataFactory = field.getAnnotation(DataFactory.class);
 if (dataFactory != null &amp;&amp; dataFactory.data() != IData.class) {
 value = ClassUtil.newInstance(dataFactory.data()).build(context, fieldClass);
 } else if (dataFactory != null) {
 // 默认的实现
 DefaultDataFactoryAnnotationData annotationData = new DefaultDataFactoryAnnotationData();
 value = annotationData.build(context, fieldClass);
 }
             // 是否为自定义注解             IAnnotationData annotationData = InnerDataUtil.getDefineDataAnnotation(field);             if (annotationData != null) {                 value = annotationData.build(context, fieldClass);             }`  
如果不加注解，这样全部都为null了，应该有个兜底的方案吧？ 默认是随机参数，如果有注解就生成注解参数，如果有自定义就生成自定义。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by longchuan90** [comment]
增加@DataFactory 后
`Exception in thread "main" java.lang.NullPointerException
	at com.github.houbb.data.factory.core.api.data.annotation.DefaultDataFactoryAnnotationData.buildDataValue(DefaultDataFactoryAnnotationData.java:38)
	at com.github.houbb.data.factory.core.api.data.annotation.DefaultDataFactoryAnnotationData.buildDataValue(DefaultDataFactoryAnnotationData.java:22)
	at com.github.houbb.data.factory.core.api.data.annotation.AbstractAnnotationData.build(AbstractAnnotationData.java:54)
	at com.github.houbb.data.factory.core.api.data.aggregate.BeanData.getFieldDataValue(BeanData.java:83)
	at com.github.houbb.data.factory.core.api.data.aggregate.BeanData.build(BeanData.java:47)
	at com.github.houbb.data.factory.core.core.Data.build(Data.java:24)
	at com.github.houbb.data.factory.core.util.DataUtil.build(DataUtil.java:37)
	at com.github.houbb.data.factory.core.api.data.aggregate.IterableData.build(IterableData.java:42)
	at com.github.houbb.data.factory.core.api.data.aggregate.IterableData.build(IterableData.java:25)
	at com.github.houbb.data.factory.core.core.Data.build(Data.java:24)
	at com.github.houbb.data.factory.core.util.DataUtil.build(DataUtil.java:37)
	at com.github.houbb.data.factory.core.api.data.aggregate.BeanData.getFieldDataValue(BeanData.java:90)
	at com.github.houbb.data.factory.core.api.data.aggregate.BeanData.build(BeanData.java:47)
	at com.github.houbb.data.factory.core.core.Data.build(Data.java:24)
	at com.github.houbb.data.factory.core.util.DataUtil.build(DataUtil.java:37)
	at com.github.houbb.data.factory.core.util.DataUtil.build(DataUtil.java:24)`
